spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/todo1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hbm2ddl.auto: validate
    show-sql: true
